main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('random-quote/', views.random_quote_view, name='random_quote'),
]

newsapp/urls.py
from django.urls import path
from . import views

app_name = "newsapp"

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path(
        'news/<str:category>/',
        views.NewsView.as_view(),
        name='news_by_category'
    ),
    path(
        'exchange-rates/',
        views.ExchangeRatesView.as_view(),
        name='exchange_rates'
    ),
    path(
        'convert-currency/',
        views.ConvertCurrencyView.as_view(),
        name='convert_currency'
    ),
    path(
        'weather/',
        views.WeatherView.as_view(),
        name='weather'
    ),
    path(
        'set_timezone/',
        views.set_timezone,
        name='set_timezone'
    ),
]

nexus_suite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
    path('quotes/', include('quotes.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignupUserView.as_view(), name='signup'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('profile/', views.UpdateUserProfileView.as_view(), name='profile'),
    # path(
    #     'password_reset/',
    #     views.CustomPasswordResetRequestView.as_view(),
    #     name='password_reset'
    # ),
    # path(
    #     'password_reset/done/',
    #     views.CustomPasswordResetDoneView.as_view(),
    #     name='password_reset_done'
    # ),
    # path(
    #     'password/reset/<uidb64>/<token>/',
    #     views.CustomPasswordResetConfirmView.as_view(),
    #     name='password_reset_confirm'
    # ),
    # path(
    #     'password/reset/complete/',
    #     views.CustomPasswordResetCompleteView.as_view(),
    #     name='password_reset_complete'
    # ),
]

newsapp/views.py
from django.views import View
from django.core.cache import cache
from django.shortcuts import render, redirect
from django.utils import timezone

from asgiref.sync import sync_to_async
import logging
import pytz

from .utils.translations import translations
from .utils.utils import (
    get_translated_day_and_month, get_language,
    set_timezone, get_update_times
)
from .utils.location_utils import (
    COUNTRIES, COUNTRIES_UA, COUNTRIES_GENITIVE_UA
)
from .utils.weather_utils import fetch_weather_data
from .utils.exchanger_utils import (
    CURRENCY_MAP, fetch_exchange_rates, convert_currency
)
from .utils.news_utils import CATEGORY_MAP, fetch_news_by_category
from .utils.location_utils import process_city_info
from .utils.exceptions import (APIError, UnableToRetrieveWeatherError)

logger = logging.getLogger(__name__)


class BaseView(View):
    """
    Base class view that includes common context setup, like date, time,
    and translations, to be used across various views.
    """

    def get_user(self, request):
        """Return the current user."""
        return request.user

    @sync_to_async
    def is_authenticated(self, request):
        """Check if the user is authenticated."""
        return request.user.is_authenticated

    def get_avatar_url(self, user):
        """
        Retrieves the avatar URL for a user.
        """
        if (
            user.is_authenticated
                and hasattr(user, 'profile')
                and user.profile.avatar
        ):
            return user.profile.avatar.url
        return None

    async def get_common_context(self, request):
        """
        Forms and returns a common context dictionary for all views.

        Parameters:
        request: User's session request object containing session data.

        Returns:
        dict: Dictionary with general data such as language, timezone,
              current date and time, and translations.
        """
        language = await sync_to_async(get_language)(request)
        transl = translations.get(language, translations['en'])

        await sync_to_async(set_timezone)(request)

        # Get user's timezone and current time
        timezone_str = (
            await sync_to_async(request.session.get)('django_timezone', 'UTC')
        )
        user_timezone = pytz.timezone(timezone_str)
        now = timezone.now().astimezone(user_timezone)

        # Translate the date and time
        translated_day, translated_month = (
            await sync_to_async(get_translated_day_and_month)(
                now, language, 'full'
            )
        )
        current_time = now.strftime('%H:%M')
        current_date = (
            f"{translated_day}, {now.day} {translated_month} {now.year}"
        )

        # Retrieve user's avatar URL
        user = await sync_to_async(self.get_user)(request)
        avatar_url = await sync_to_async(self.get_avatar_url)(request.user)

        return {
            'language': language,
            'translations': transl,
            'current_date': current_date,
            'current_time': current_time,
            'user_timezone': user_timezone,
            'user': user,
            'avatar_url': avatar_url,
        }


class MainView(BaseView):
    """
    Main view to handle the homepage, displaying weather,
    exchange rates, and news.
    """

    async def get(self, request):
        """
        Handles the GET request for rendering the homepage with weather,
        exchange rates, and news data.

        Parameters:
        request: User's session request object containing session data.

        Returns:
        HttpResponse: Rendered homepage with the fetched context.
        """
        context = await self.get_common_context(request)
        language = context['language']
        transl = context['translations']
        user_timezone = context['user_timezone']

        weather_error_message = None
        exchange_rate_error_message = None

        default_city = 'Kyiv' if language == 'en' else 'Київ'
        current_city = request.session.get('selected_city', default_city)

        # Update city to default when language is switched
        if 'language' in request.GET:
            request.session['selected_city'] = default_city
            city = default_city
        else:
            city = request.GET.get('city', current_city)
            if city != current_city:
                await sync_to_async(request.session.__setitem__)(
                    'selected_city', city
                )

        country = request.GET.get(
            'country', await sync_to_async(request.session.get)(
                'selected_country', 'us' if language == 'en' else 'ua'
            )
        )

        if language == 'en':
            await sync_to_async(request.session.__setitem__)(
                'selected_country', 'us'
            )
            country = 'us'
        else:
            await sync_to_async(request.session.__setitem__)(
                'selected_country', 'ua'
            )
            country = 'ua'

        displayed_country_name = (
            COUNTRIES_UA.get(country, 'Unknown') if language == 'uk'
            else COUNTRIES.get(country, 'Unknown')
        )
        genitive_country_name = (
            COUNTRIES_GENITIVE_UA.get(country, 'Unknown') if language == 'uk'
            else COUNTRIES.get(country, 'Unknown')
        )

        # Fetch weather data
        try:
            weather_data = await fetch_weather_data(
                city, transl, language, data_type='current'
            )
        except UnableToRetrieveWeatherError as e:
            weather_error_message = (
                transl['could_not_geocode'] % {'city': city}
            )
            logger.error(f"Weather retrieval error for {city}: {str(e)}")
            weather_data = None

        if weather_data is None:
            await sync_to_async(request.session.__setitem__)('selected_city',
                                                             default_city)

        # Fetch exchange rates
        try:
            exchange_rates = await fetch_exchange_rates(
                filter_currencies={'USD', 'EUR', 'PLN'}
            )
        except APIError as e:
            logger.error(f"Error fetching exchange rates: {str(e)}")
            exchange_rates = []
            exchange_rate_error_message = transl[
                'unable_to_fetch_exchange_rates'
            ]

        # Fetch news articles for the main page
        try:
            general_news = await fetch_news_by_category('general',
                                                        country, transl)
            articles = general_news[:10]
        except APIError as e:
            logger.error(f"Error fetching general news: {str(e)}")
            context['error_message'] = transl['unable_to_fetch_news']
            articles = []

        formatted_local_update_time, formatted_user_update_time = \
            get_update_times(weather_data, user_timezone, transl)

        context.update({
            'weather_error_message': weather_error_message,
            'weather_data': weather_data,
            'exchange_rates': exchange_rates,
            'articles': articles,
            'all_news_link': True,
            'selected_city': city,
            'selected_country': country,
            'selected_country_name': displayed_country_name,
            'genitive_country_name': genitive_country_name,
            'category_translations': {
                k: transl[k] for k in CATEGORY_MAP.keys()
            },
            'local_update_time': formatted_local_update_time,
            'user_update_time': formatted_user_update_time,
            'countries': COUNTRIES if language == 'en' else COUNTRIES_UA,
            'exchange_rate_error_message': exchange_rate_error_message,
            'is_authenticated': await self.is_authenticated(request),
        })

        return render(request, 'newsapp/index.html', context)


class WeatherView(BaseView):
    """
    View to handle weather data requests for a specific location.
    """

    async def get(self, request):
        """
        Handles the GET request for fetching and displaying
        detailed weather data.

        Parameters:
        request: User's request containing parameters like location.

        Returns:
        HttpResponse: Rendered page with detailed weather information.
        """
        context = await self.get_common_context(request)
        language = context['language']
        transl = context['translations']
        user_timezone = context['user_timezone']

        error_message = None
        default_city = 'Kyiv' if language == 'en' else 'Київ'
        city = request.session.get('selected_city', default_city)
        if 'city' in request.GET:
            city = request.GET['city']
            await sync_to_async(request.session.__setitem__)('selected_city',
                                                             city)

        try:
            weather_data = await fetch_weather_data(
                city, transl, language, data_type='both'
            )
            city, region, country_name, weather_in_text = (
                await process_city_info(
                    city,
                    weather_data['geo_city'],
                    weather_data['country_code'],
                    weather_data['geo_country'],
                    weather_data['geo_region'],
                    weather_data['api_country'],
                    weather_data['api_region'],
                    language,
                    transl
                )
            )

            formatted_local_update_time, formatted_user_update_time = \
                get_update_times(weather_data, user_timezone, transl)

        except UnableToRetrieveWeatherError:
            error_message = transl['could_not_geocode'] % {'city': city}
            weather_data = None
            country_name = None
            region = None

newsapp/templates/newsapp/base.html
<!DOCTYPE html>
<html lang="{{ request.session.language|default:'en' }}">

<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Personal Assistant App{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&family=Roboto:wght@400;500;700;900&display=swap"
        rel="stylesheet" />
    <!-- <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/> -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'newsapp/styles.css' %}">
    <link rel="icon" href="{% static 'newsapp/favicon.ico' %}">
    {% block style %}{% endblock %}
    {% block script %}{% endblock %}
</head>

<body>
    <header class="header">
        <div class="top-bar flex-container">
            <div class="date-time">
                <span>{{ current_time }} - {{ current_date }}</span>
            </div>
            <a href="?lang={% if request.session.language == 'en' %}uk{% else %}en{% endif %}" class="language">
                {% if request.session.language == 'en' %}
                Українською
                {% else %}
                English
                {% endif %}
            </a>
        </div>
        <nav class="nav-bar flex-container">
            <a class="brand" href="{% url 'newsapp:index' %}">
                <span class="accent">Nexus</span>Suite
            </a>

            <div class="auth-links">
                {% if request.user.is_authenticated %}
                <a href="{% url 'users:profile' %}">
                    <img src="{{ avatar_url }}" alt="Avatar" class="avatar-img">
                </a>
                <span>{{ translations.welcome }}, <b>{{ user.username }}!</b></span>
                <a href="{% url 'users:logout' %}">{{ translations.logout }}</a>
                {% else %}
                <a href="{% url 'users:signup' %}">{{ translations.sign_up }}</a>
                <a href="{% url 'users:login' %}">{{ translations.login }}</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <div class="content-container">
        {% block content %} {% endblock %}
    </div>

</body>

</html>

newsapp/templates/newsapp/category_news.html
{% extends "newsapp/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}{{ translations.todays_news_from }} {{ category_translations|get_item:selected_category }}{% endblock %}

{% block content %}

<main>
    {% if error_message %}
    <h1>{{ translations.unable_to_fetch_news }}</h1>
    {% else %}
    <h1>{{ category_title }}</h1>
    {% endif %}
    <section class="news-section">
        <ul class="news-list">
            {% for article in articles %}
            <li class="news-item">
                <div class="news-time">
                    <small>
                        {{ article.published_at|format_time_filter:request.session.language }}
                    </small>
                </div>
                <div class="news-content">
                    <a href="{{ article.url }}">{{ article.title }}</a>
                    <span>({{ article.source }})</span>
                </div>
            </li>
            {% endfor %}
        </ul>
    </section>
</main>

<aside>
    <div class="sidebar-container">
        <h2 for="country">{{ translations.select_news_country }}</h2>
        <form method="GET" action="{% url 'newsapp:news_by_category' selected_category %}" class="sidebar-container-form news-form">
            <div class="form-group">
                <select id="country" name="country">
                    {% for code, name in countries.items %}
                    <option value="{{ code }}" {% if code == selected_country %}selected{% endif %}>{{ name }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="submit-button">{{ translations.update_news }}</button>
        </form>
    </div>
    <h2>{{ translations.categories }}</h2>
    <ul class="category-list">
        {% for category in categories %}
        <li class="category-item">
            <a href="{% url 'newsapp:news_by_category' category %}"
                class="{% if category == selected_category %}active{% endif %}">
                {{ category_translations|get_item:category }}
            </a>
        </li>
        {% endfor %}
    </ul>
</aside>

{% endblock content %}

newsapp/templates/newsapp/exchange_rates.html
{% extends "newsapp/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}{{ translations.exchange_rates }}{% endblock %}

{% block content %}

<main>
    <h1>{{ translations.exchange_rates }}</h1>
    <div class="currency-description">
        {% if language == 'uk' %}
        <p>
            Ця сторінка надає актуальні курси валют до гривні, зокрема курси від <a href="https://bank.gov.ua/ua/markets/exchangerates">Національного банку України</a> та <a href="https://privatbank.ua">Приватбанку</a>.
            Ви можете ознайомитися з курсами купівлі та продажу валют, а також скористатися вбудованим конвертером валют.
            Інтерфейс дає змогу зручно порівняти різні валюти та перевести їх до гривні або між собою.</p>

        {% else %}
        <p>
            This page provides the current exchange rates for the Ukrainian Hryvnia, including rates from the <a href="https://bank.gov.ua/en/markets/exchangerates">National Bank of Ukraine</a> and <a href="https://privatbank.ua/en">PrivatBank</a>.
            You can view both the buying and selling exchange rates, as well as use the built-in currency converter.
            The interface allows you to compare different currencies and convert them to Hryvnia or between currencies.
        </p>
        {% endif %}
    </div>

    {% if error_message %}
    <div class="alert-error">
        {{ error_message }}
    </div>
    {% else %}
    <section class="exchange-rates-section">
        <table class="exchange-rates-table">
            <thead>
                <tr>
                    <th>{{ translations.currency }}</th>
                    <th>{{ translations.code }}</th>
                    <th>{{ translations.rate_nb }}</th>
                    <th>{{ translations.purchase_rate }}</th>
                    <th>{{ translations.sale_rate }}</th>
                </tr>
            </thead>
            <tbody>
                {% for rate in exchange_rates %}
                <tr class="{% cycle 'even' 'odd' %}">
                    <td>{{ currency_names|get_item:rate.currency }}</td>
                    <td>{{ rate.currency }}</td>
                    <td class="rate-value">{{ rate.saleRateNB }}</td>
                    <td class="rate-value">{{ rate.purchaseRate|default_if_none:"-" }}</td>
                    <td class="rate-value">{{ rate.saleRate|default_if_none:"-" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
    {% endif %}
</main>

<aside>
    <section class="sidebar-container">
        <h2>{{ translations.currency_converter }}</h2>
        <form method="POST" action="{% url 'newsapp:convert_currency' %}" class="sidebar-container-form converter-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="from_currency">{{ translations.from_currency }}</label>
                <select id="from_currency" name="from_currency">
                    <option value="UAH">{{ translations.currency_uah }}</option>
                    {% for rate in exchange_rates %}
                    <option value="{{ rate.currency }}" {% if rate.currency == from_currency %}selected{% endif %}>
                        {{ currency_names|get_item:rate.currency }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="to_currency">{{ translations.to_currency }}</label>
                <select id="to_currency" name="to_currency">
                    <option value="UAH">{{ translations.currency_uah }}</option>
                    {% for rate in exchange_rates %}
                    <option value="{{ rate.currency }}" {% if rate.currency == to_currency %}selected{% endif %}>
                        {{ currency_names|get_item:rate.currency }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group amount-field">
                <label for="amount">{{ translations.amount }}</label>
                <input type="number" id="amount" name="amount" value="{{ amount|default:0 }}" required>
            </div>
            {% if conversion_error_message %}
            <div class="alert-error">
                {{ conversion_error_message }}
            </div>
            {% endif %}
            <div class="form-group amount-field">
                <label for="converted_amount">{{ translations.converted_amount }}</label>
                <input type="text" id="converted_amount" name="converted_amount" value="{{ converted_amount }}" readonly
                    class="converter-result">
            </div>
            <button type="submit" class="submit-button">{{ translations.convert }}</button>
        </form>
    </section>
</aside>

{% endblock content %}

newsapp/templates/newsapp/index.html
{% extends "newsapp/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}NexusSuite{% endblock %}

{% block content %}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        fetch(`/set_timezone/?timezone=${timezone}`, { method: 'GET' });
    });
</script>

<main>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <h1>
        <a href="{% url 'newsapp:news_by_category' 'general' %}" class="header-link">
            {{ translations.todays_news }}
        </a>
        {{ translations.from }}
        {{ genitive_country_name }}
    </h1>
    {% if error_message %}
    <p>{{ translations.unable_to_fetch_news }}</p>
    {% else %}
    <section class="news-section">
        <ul class="news-list">
            {% for article in articles %}
            <li class="news-item">
                <div class="news-time">
                    <small>
                        {{ article.published_at|default_if_none:"N/A"|format_time_filter:request.session.language }}
                    </small>
                </div>
                <div class="news-content">
                    <a href="{{ article.url }}">{{ article.title }}</a>
                    <span>({{ article.source }})</span>
                </div>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'newsapp:news_by_category' 'general' %}" class="view-more">
            {{ translations.all_main_news }}
        </a>
    </section>
    {% endif %}
</main>

<aside>
    <div class="sidebar-container weather-box">
        <div class="flex-container weather-header">
            <span class="city_name">{{ selected_city }}</span>
            <div>
                <a href="{% url 'newsapp:weather' %}" class="header-link">{{ translations.weather }} ></a>
            </div>
        </div>
        {% if weather_data %}
        <p class="time">{{ user_update_time }}</p>
        <div class="weather-details">
            <div class="main-info">
                <div class="temperature">
                    <div class="temp-value">
                        {{ weather_data.current.temperature_c }}<sup class="temp-unit">°C</sup>
                    </div>
                </div>
                <img src="{{ weather_data.current.icon_url }}" alt="Weather Icon">
                <div class="other-details">
                    <p><span>{{ translations.humidity_ix }}</span>:
                        <strong>{{ weather_data.current.humidity }}%</strong>
                    </p>
                    <p><span>{{ translations.pressure_ix }}</span>:
                        <strong>{{ weather_data.current.pressure_mm }} {{translations.mmHg }}</strong>
                    </p>
                    <p><span>{{ translations.wind_ix }}</span>:
                        <strong>{{ weather_data.current.wind_mps }} {{ translations.mps }}</strong>
                    </p>
                </div>
            </div>
            <p class="condition"><strong>{{ weather_data.current.condition }}</strong></p>
        </div>
        {% else %}
        <p>{{ translations.unable_to_retrieve_weather }}.</p>
        {% if weather_error_message %}
        <div class="alert-error">{{ weather_error_message }}</div>
        {% endif %}
        {% endif %}

        <div class="weather-form-container">
            <form method="GET" action="{% url 'newsapp:index' %}" class="sidebar-container-form weather-form">
                <input type="hidden" name="country" value="{{ selected_country }}">
                <div class="form-group">
                    <input type="text" id="city" name="city" placeholder="{{ translations.enter_city_name }}"
                        value="{{ selected_city }}" required>
                </div>
                <button type="submit" class="submit-button">{{ translations.update_weather }}</button>
            </form>
        </div>
    </div>
    <div class="sidebar-container exchange-rates-box">
        {% if exchange_rate_error_message %}
        <div class="alert-error">
            {{ exchange_rate_error_message }}
        </div>
        {% else %}
        <div class="exchange-rates-header">
            <a href="{% url 'newsapp:exchange_rates' %}" class="header-link">{{ translations.exchange_rates }}
                ></a>
        </div>
        <table class="exchange-rates-table">
            <thead>
                <tr>
                    <th></th>
                    <th>{{ translations.rate }}</th>
                    <th>{{ translations.purchase }}</th>
                    <th>{{ translations.sale }}</th>
                </tr>
            </thead>
            <tbody>
                {% for rate in exchange_rates %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td>{{ rate.currency }}</td>
                    <td class="rate-value">{{ rate.saleRateNB }}</td>
                    <td class="rate-value">{{ rate.purchaseRate|default_if_none:"-" }}</td>
                    <td class="rate-value">{{ rate.saleRate|default_if_none:"-" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

</aside>
{% endblock %}

</html>